services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres_password
      DATABASE_NAME: sakila
  database:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: sakila
