services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
  database:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

  database-migrations:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    command: ["python", "-m", "alembic", "upgrade", "head"]
    env_file:
      - .env
    environment:
      DATABASE_HOST: database
    depends_on:
      database:
        condition: service_healthy
