services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgrespassword
      DATABASE_NAME: sakila
  database:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: sakila
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

  database-migrations:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    command: ["python", "-m", "alembic", "upgrade", "head"]
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgrespassword
      DATABASE_NAME: sakila
    depends_on:
      database:
        condition: service_healthy
