apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  labels:
    app.kubernetes.io/name: myapi
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapi
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/serpentsparker/fastapi-demo:0.2.0
          command: ["python", "-m", "alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: myapi
          image: ghcr.io/serpentsparker/fastapi-demo:0.2.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
