apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: myapi
data:
  POSTGRES_DB: myapi
  POSTGRES_USER: postgres
