# This workflow will lint the Python modules, install dependencies, and run tests with a single version of Python.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python.

name: Python Linting and Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint the Python application with ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: "./myapi"
          args: "--output-format=github"

      - name: Format the Python modules with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project dependencies
        run: uv sync --all-extras --dev

      - name: Run Python tests with pytest
        run: uv run python -m pytest tests
